# Generated by Django 6.0.4 on 2026-04-18 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_range', models.CharField(blank=True, choices=[('seed', 'Seed Stage'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('growth', 'Growth Stage')], max_length=50)),
                ('industries', models.TextField(help_text='Interest in industries')),
                ('portfolio_link', models.URLField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('negotiating', 'Negotiating'), ('completed', 'Completed'), ('declined', 'Declined')], default='interested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup_founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_investments', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investor.investor')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
