# Generated by Django 5.2 on 2026-04-18 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, help_text="Investor's company name", max_length=100)),
                ('meeting_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('followup', 'Follow-up'), ('passed', 'Passed')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Meeting notes and outcomes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='PitchDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_default=models.Value('v1.0'), max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('ready', 'Ready')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the pitch deck')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_deck', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pitch Decks',
            },
        ),
    ]
