# Generated by Django 5.2 on 2026-04-18 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_investormeeting_pitchdeck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pitchdeck',
            options={'verbose_name': 'Pitch Deck', 'verbose_name_plural': 'Pitch Decks'},
        ),
        migrations.AddField(
            model_name='investormeeting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pitchdeck',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='investment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='investment',
            name='percentage',
            field=models.DecimalField(db_default=0, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('interested', 'Interested'), ('negotiating', 'Negotiating'), ('completed', 'Completed'), ('declined', 'Declined')], db_default='interested', max_length=20),
        ),
        migrations.AlterField(
            model_name='investor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='investor',
            name='verified',
            field=models.BooleanField(db_default=False),
        ),
        migrations.AlterField(
            model_name='investormeeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('followup', 'Follow-up'), ('passed', 'Passed')], db_default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='pitchdeck',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('ready', 'Ready')], db_default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='pitchdeck',
            name='version',
            field=models.CharField(db_default='v1.0', max_length=20),
        ),
    ]
