# Generated by Django 5.2 on 2026-04-18 17:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_default=models.Value(datetime.datetime(2026, 4, 18, 17, 15, 6, 534894, tzinfo=datetime.timezone.utc)))),
                ('tasks_completed', models.IntegerField(db_default=0)),
                ('tasks_total', models.IntegerField(db_default=0)),
                ('note', models.TextField(blank=True, help_text='Daily note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
