# Generated by Django 5.2 on 2026-04-19 01:15

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_dailyprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogress',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='progressmetric',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='progressmetric',
            name='current_value',
            field=models.DecimalField(db_default=0, decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='progressmetric',
            name='metric_type',
            field=models.CharField(choices=[('revenue', 'Revenue'), ('users', 'Users'), ('engagement', 'Engagement'), ('custom', 'Custom')], db_default='custom', max_length=50),
        ),
    ]
