# Generated by Django 5.2 on 2026-04-18 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_mentorfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('limited', 'Limited Availability'), ('unavailable', 'Unavailable')], db_default='available', max_length=50),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='verified',
            field=models.BooleanField(db_default=False),
        ),
        migrations.AlterField(
            model_name='mentorfeedback',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mentorsession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mentorsession',
            name='duration_minutes',
            field=models.IntegerField(db_default=60),
        ),
        migrations.AlterField(
            model_name='mentorsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_default='scheduled', max_length=20),
        ),
    ]
