# Generated by Django 5.2 on 2026-04-19 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_alter_mentor_availability_alter_mentor_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorfeedback',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_given', to='mentor.mentor'),
        ),
        migrations.AlterField(
            model_name='mentorfeedback',
            name='mentor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
