# Generated by Django 5.2 on 2026-04-18 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_startupprofile_delete_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='kpi_revenue',
            field=models.DecimalField(db_default=0, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='kpi_users',
            field=models.IntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='stage',
            field=models.CharField(choices=[('idea', 'Idea'), ('mvp', 'MVP'), ('growth', 'Growth')], db_default='idea', max_length=20),
        ),
    ]
