# Generated by Django 6.0.4 on 2026-04-19 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_remove_user_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, db_default='', help_text='Maximum file size: 5MB. Formats: JPG, PNG, GIF', upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'], message='Only JPG, PNG, and GIF image files are allowed')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, db_default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_investor',
            field=models.BooleanField(db_default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_mentor',
            field=models.BooleanField(db_default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='startup_name',
            field=models.CharField(blank=True, db_default='', max_length=100),
        ),
    ]
